# -*- coding: utf-8 -*-
"""
Content data for the 21-day "Yes to Jesus" devotional.
Adapted from Life.Church's "You Said Yes" (Open Network), used with attribution.
Each scripture reference includes a YouVersion (bible.com) deep-link so readers
can jump straight into the YouVersion Bible App / bible.com for full context.
"""

# YouVersion translation -> version_id (bible.com numeric IDs)
VERSIONS = {
    "NIV": 111,
    "NLT": 116,
    "MSG": 97,
}


def yv_link(book, chapter_verse, translation):
    """Build a bible.com deep link, e.g. yv_link('JHN', '3.16-17', 'NLT')"""
    vid = VERSIONS.get(translation, 111)
    return f"https://www.bible.com/bible/{vid}/{book}.{chapter_verse}.{translation}"


DAYS = [
    # ---------------- WEEK 1: Starting to Follow Jesus ----------------
    {
        "day": 1,
        "week": 1,
        "slug": "what-does-it-mean-to-say-yes-to-jesus",
        "title": "What Does It Mean to Say Yes to Jesus?",
        "summary": "You said yes to Jesus. Here's what that decision actually means, and why God's love makes it worth it.",
        "scripture": [{"ref": "John 3:16-17", "translation": "NLT", "link": yv_link("JHN", "3.16-17", "NLT")}],
        "body": [
            "You said yes to Jesus—and we're really proud of you.",
            "There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”",
            "But what does it mean to follow Jesus? What changes and what doesn't? Why? Those are some of the questions this book will help you answer.",
            "So, let's start with that first question. What does it mean to say yes to Jesus? Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him?",
            "To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.",
            "Centuries later, God's Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.",
            "Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus' questions, Jesus shared some of His most famous words:",
        ],
        "quote": {"text": "For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.", "ref": "John 3:16-17 NLT"},
        "closing": "God's love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That's the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life. Tomorrow, we'll talk about how that happens, but today, let's consider Jesus' answer as we talk with Him in prayer.",
        "prayer": "God, I have decided to trust that Jesus is Your Son who came to save me and the world. I don't know everything about what this means yet, but I do want to follow Jesus and live His way. Thank You for loving me enough to send Jesus. Thank You for inviting me into Your family. Amen.",
    },
    {
        "day": 2,
        "week": 1,
        "slug": "what-happens-after-i-say-yes-to-jesus",
        "title": "What Happens After I Say Yes to Jesus?",
        "summary": "Becoming more like Jesus is a process—God does the heavy lifting, but we get to partner with Him in the work.",
        "scripture": [{"ref": "1 John 2:2, 5-6", "translation": "MSG", "link": yv_link("1JN", "2.2", "MSG")}],
        "body": [
            "Yesterday we ended with prayer, and today we'll start with it. God likes hearing from us anytime.",
        ],
        "prayer_intro": "God, thank You for the gift of salvation: saving me from myself and bringing me into a healing relationship with You. Use Your love to shape me today, in the coming weeks, and for the rest of my life. I'm trusting You to make me new. In Jesus' name, amen.",
        "body2": [
            "Christians finish prayers in Jesus' name because this is one of the ways Jesus told us to pray. We're able to connect with God on a first-name basis because of Jesus' sacrifice for our sins. And we need this kind of connection if we're going to live our lives His way and become more like Him.",
            "Jesus lived His life with integrity. He loved His enemies, pushed back against injustice, and welcomed people that culture rejected. After we say yes to Jesus, we start the lifelong process of following Him. So, over time, we begin taking on those same traits. In fact, when Jesus summed up all of the commandments in the Bible, He asked us to love God with all we are and to love our neighbors as ourselves.",
            "But is that process automatic, or is it something we have a role in making happen? It's not one or the other—it's both.",
        ],
        "quote": {"text": "When he served as a sacrifice for our sins, he solved the sin problem for good—not only ours, but the whole world's. … This is the only way to be sure we're in God. Anyone who claims to be intimate with God ought to live the same kind of life Jesus lived.", "ref": "1 John 2:2, 5-6 MSG"},
        "closing": "Becoming more like Jesus is a process. God does the heavy lifting, but we can partner with Him in the work He's doing. And for the rest of our journey together, we're going to look at three ways we can do that:",
        "list": [
            "Learning some of the basics of following Jesus—Who is God? What does it look like to talk to God and learn more about Him? What are some good next steps we can take? We'll spend the rest of this week answering important questions like these.",
            "Living like Jesus lived—During Jesus' time on Earth, He modeled many ways of living that can bring us closer to God, help us connect with Him, and live like Him. These are called spiritual practices. We'll spend week two exploring some of these practices.",
            "Loving like Jesus loved—Nothing makes us grow more like Jesus than loving like He loved. During week three, we'll take a look at what it means to put Jesus' love into practice.",
        ],
        "reflection": "Which parts of my life do I hope God will make new? How do I want to partner with God to care for others and the world around me?",
    },
    {
        "day": 3,
        "week": 1,
        "slug": "who-is-god",
        "title": "Who Is God?",
        "summary": "God is Father, Son, and Holy Spirit—three in one. Here's what that means for you.",
        "scripture": [
            {"ref": "Genesis 1:1-2", "translation": "NIV", "link": yv_link("GEN", "1.1-2", "NIV")},
            {"ref": "John 1:1-2, 12, 14, 18, 33-34", "translation": "NIV", "link": yv_link("JHN", "1.1-2", "NIV")},
        ],
        "body": [
            "Is God: God the Father? Jesus the Son? The Holy Spirit? All three in one? Yes!",
            "Choosing to follow Jesus is a three-in-one decision: You are accepting the invitation through Jesus (the Son of God) to become a child of God the Father, filled with the Holy Spirit, and empowered to live as a daughter or son of God. God is three in one.",
            "We can see God reflected this way, as the Trinity, all throughout the Bible. The Spirit of God was present with God the Father from the beginning of Creation, as seen in the first two sentences of the Bible.",
        ],
        "quote": {"text": "In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters.", "ref": "Genesis 1:1-2 NIV"},
        "body2": [
            "Later, the author of John retells the story of Creation. This time, Jesus is also mentioned and the author refers to Him as God's Word. You'll definitely want to get a Bible or download the Bible App from YouVersion to read all of the book of John soon. Here are a few verses from John 1 that describe the three parts of God's being:",
        ],
        "quote2": {"text": "In the beginning was the Word, and the Word was with God, and the Word was God. He was with God in the beginning. ... to all who did receive him, to those who believed in his name, he gave the right to become children of God ... The Word became flesh and made his dwelling among us. We have seen his glory, the glory of the one and only Son, who came from the Father, full of grace and truth. ... No one has ever seen God, but the one and only Son, who is himself God and is in closest relationship with the Father, has made him known. ... ‘The man on whom you see the Spirit come down and remain is the one who will baptize with the Holy Spirit.' I have seen and I testify that this is God's Chosen One.", "ref": "John 1:1-2, 12, 14, 18, 33-34 NIV"},
        "closing": "That's a lot. Here's the takeaway: Jesus, God the Father, and the Holy Spirit are One, and Jesus came not just to show us what God is like, but to give us direct access to the Father forever, through the Holy Spirit.",
        "prayer": "God, help me to know You as Father, Son, and Holy Spirit. Father, You are my Provider. Jesus, You are my Savior. Holy Spirit, You are my Guide. In Jesus' name, amen.",
    },
    {
        "day": 4,
        "week": 1,
        "slug": "how-does-god-guide-us",
        "title": "How Does God Guide Us?",
        "summary": "The Holy Spirit is your Comforter, Advocate, Helper, and Friend—and God chooses to live within you.",
        "scripture": [
            {"ref": "John 14:16-17", "translation": "NIV", "link": yv_link("JHN", "14.16-17", "NIV")},
            {"ref": "John 16:7", "translation": "MSG", "link": yv_link("JHN", "16.7", "MSG")},
            {"ref": "John 14:18-20", "translation": "NIV", "link": yv_link("JHN", "14.18-20", "NIV")},
            {"ref": "John 14:26", "translation": "MSG", "link": yv_link("JHN", "14.26", "MSG")},
        ],
        "body": [
            "Yesterday we prayed: God, help me get to know You as Father, Son, and Holy Spirit. Holy Spirit, You are my Guide.",
            "Who is the Holy Spirit, and how does He guide us? Do we have to act really spiritual to get the Spirit's attention? Jesus promised something different.",
            "Jesus described the Holy Spirit as a comforter, advocate, helper, and friend. Do you know anyone like that? Maybe a mentor, mother, or wise friend? As you read Jesus' words, think about the Holy Spirit as your Comforter, Advocate, Helper, and Friend.",
        ],
        "quote": {"text": "“And I will ask the Father, and he will give you another advocate to help you and be with you forever—the Spirit of truth. The world cannot accept him, because it neither sees him nor knows him. But you know him, for he lives with you and will be in you.”", "ref": "John 14:16-17 NIV"},
        "body2": [
            "Jesus made this promise to His followers while telling them He would soon leave to be with the Father.",
        ],
        "quote2": {"text": "“So let me say it again, this truth: It's better for you that I leave. If I don't leave, the Friend won't come. But if I go, I'll send him to you.”", "ref": "John 16:7 MSG"},
        "body3": [
            "His followers might have felt confused, worried, or even abandoned, but Jesus clarified that His physical leaving was less about going away and more about coming closer.",
        ],
        "quote3": {"text": "“I will not leave you as orphans; I will come to you. Before long, the world will not see me anymore, but you will see me. Because I live, you also will live. On that day you will realize that I am in my Father, and you are in me, and I am in you.”", "ref": "John 14:18-20 NIV"},
        "body4": [
            "Jesus was coming closer because the Holy Spirit would not only be with us, but in us: The Spirit did what Jesus promised and came to fill His followers with the same comfort, power, and love that filled Jesus.",
            "By saying yes to living Jesus' way, we invite the Holy Spirit to help, comfort, and advocate for and through us.",
        ],
        "quote4": {"text": "“The Friend, the Holy Spirit whom the Father will send at my request, will make everything plain to you. He will remind you of all the things I have told you.”", "ref": "John 14:26 MSG"},
        "closing": "God chooses to live within us and guide us. In the coming weeks, we will identify practices for becoming more hospitable to God's presence in our lives.",
        "prayer": "God, thank You for the Holy Spirit. Will You continue to help me know You as Comforter, Helper, Advocate, and Friend? I trust You to guide me as I follow the way of Jesus. In Jesus' name, amen.",
    },
    {
        "day": 5,
        "week": 1,
        "slug": "what-is-baptism",
        "title": "What Is Baptism?",
        "summary": "Baptism is a public way Jesus followers declare their decision to follow Jesus—a picture of His death, resurrection, and your new life.",
        "scripture": [{"ref": "Matthew 3:13-17", "translation": "MSG", "link": yv_link("MAT", "3.13-17", "MSG")}, {"ref": "Matthew 28:19", "translation": "MSG", "link": yv_link("MAT", "28.19", "MSG")}],
        "body": [
            "In the last few days, we've learned about God's three-in-one nature—the Father, Son, and Holy Spirit—and how God lives in us today through the Holy Spirit. Today, we'll read another story from the Bible with all three parts of the Trinity.",
            "The main topic we're exploring today is baptism. Baptism is a public way Jesus followers declare their decision to follow Jesus. A pastor or trusted friend stands with you in a pool (or other body of water) and helps you lean back into the water and come right back up and out.",
            "But why go underwater? It's a symbol representing Jesus' death, resurrection, and new life through Him.",
        ],
        "list": [
            "Leaning back under the water symbolizes your sins being washed away through Jesus' death.",
            "Being raised out of the water is a picture of being brought back to a new life, like Jesus was raised back to life.",
        ],
        "body2": [
            "This public declaration of our new life with Jesus is similar to the way Jesus Himself was baptized.",
        ],
        "quote": {"text": "Jesus then appeared, arriving at the Jordan River from Galilee. He wanted John to baptize him. John objected, “I'm the one who needs to be baptized, not you!” But Jesus insisted. “Do it. God's work, putting things right all these centuries, is coming together right now in this baptism.” So John did it. The moment Jesus came up out of the baptismal waters, the skies opened up and he saw God's Spirit—it looked like a dove—descending and landing on him. And along with the Spirit, a voice: “This is my Son, chosen and marked by my love, delight of my life.”", "ref": "Matthew 3:13-17 MSG"},
        "body3": [
            "Now, reread the story and imagine yourself as the person being baptized by John. What's the water like? How does it feel to hear God's approval? What does God's voice say to you specifically? How do you notice the Holy Spirit's presence?",
            "At the end of Jesus' time on Earth, He gathered His followers together and shared this mission:",
        ],
        "quote2": {"text": "“Go out and train everyone you meet, far and near, in this way of life, marking them by baptism in the threefold name: Father, Son, and Holy Spirit.”", "ref": "Matthew 28:19 MSG"},
        "closing": "When you've said yes to Jesus' way of life, baptism is one of the next steps you're invited to take. Remember, it's a public declaration that says to the world, “I have decided to follow Jesus!”",
        "reflection": "Have you been baptized? What would it be like for you to take this next step of following Jesus? What questions do you still have about baptism?",
    },
    {
        "day": 6,
        "week": 1,
        "slug": "how-do-i-get-to-know-god",
        "title": "How Do I Get to Know God?",
        "summary": "We get to know God through prayer, reading the Bible, and gathering with other Jesus followers.",
        "scripture": [{"ref": "Hebrews 10:24-25", "translation": "NLT", "link": yv_link("HEB", "10.24-25", "NLT")}],
        "body": [
            "How do you get to know someone? Most of us get to know a new friend by asking questions, spending time together, and sharing meaningful stories from our lives.",
            "But interacting with God can feel a little different than getting tacos and talking with your friends. So how do we get to know God?",
        ],
        "list_headed": [
            {"head": "1. We spend time with God through prayer.", "body": "Prayer is a great way to share experiences, conversations, excitement, needs, and trust-building moments with God. How do you pray? Prayer is communicating with God. You might thank Him for who He is, ask for support, or simply be silent in God's presence. Prayer isn't a performance, so you don't need to worry about saying the “wrong” things. Instead, it's a way to relate to God, who loves you. So be honest. If it matters to you, then share it with God. Finally, God's Spirit lives in you, so pay attention to ways God may be trying to get your attention as you pray and throughout your day."},
            {"head": "2. We read the Bible.", "body": "The Bible is a collection of books written by people thousands of years ago. So, why should we read it today? We'll talk more about the Bible later, but here are some basics. The Bible helps us to see what God is like and how people like us have come to know Him. Its authors, guided by the Holy Spirit, tell stories of God's goodness, ask relatable questions, and engage with the hardest parts of life. Throughout the Bible, we get to see God's qualities, like His kindness, forgiveness, and justice. And we get to see those qualities lived through the life of Jesus."},
            {"head": "3. We gather with other Jesus followers.", "body": "Getting to know God is about “Jesus and me” and “Jesus and we.” The Bible reminds us very practically how to follow Jesus and get to know God together."},
        ],
        "quote": {"text": "Let us think of ways to motivate one another to acts of love and good works. And let us not neglect our meeting together ...", "ref": "Hebrews 10:24-25 NLT"},
        "closing": "We get to know Him better by hearing stories of God's faithfulness, listening to wisdom from the Bible, and singing songs about God's love. A very doable way to build a habit of meeting with Jesus followers is to regularly attend church. It's an opportunity to make friends, share how God's working in your life, and practice serving and encouraging others. If you haven't yet, make a plan to meet others at church this week. Consider inviting a friend, family member, or neighbor so they can experience the life-changing way of Jesus.",
    },
    {
        "day": 7,
        "week": 1,
        "slug": "what-am-i-learning",
        "title": "What Am I Learning?",
        "summary": "A week-one check-in: God loves us, forgives us, and provides us with a purpose—to become more like Jesus every day.",
        "scripture": [{"ref": "Philippians 1:6", "translation": "NIV", "link": yv_link("PHP", "1.6", "NIV")}],
        "body": [
            "Congratulations! You've made it to the end of week one. We're so proud of you for taking intentional steps to grow in your faith.",
            "Deciding to follow Jesus is a big decision, and it's probably stirred up some new ideas, questions, and perhaps doubts. That's okay. Remember, following Jesus is a lifelong journey, so we don't need to have all the mysteries of faith figured out after one week.",
            "With all of that in mind—how are you doing? Take a moment to write down two or three words or phrases to describe how you feel about your faith journey. Maybe you feel excited and expectant, or you might feel a little uncertain. You might not even be able to describe exactly how you're feeling.",
            "Don't worry about having a “right” answer. Your honest answer is the best answer. You don't need to share these words with anyone; this is simply a chance for you to reflect.",
            "In the past week, we've seen that God loves us, forgives us, and provides us with a purpose—to become more like Jesus every day. We've also seen that He wants to have a close relationship with us, so He's provided us with ways to relate to Him.",
            "We've only scratched the surface of all there is to know about following Jesus, and we're excited to continue this journey together.",
            "As we conclude week one and get ready for week two, think about and write down a question or two you might have about God, faith, or the Bible. Then, share your question with a pastor or trusted friend sometime this week.",
            "Read the verse below and think about it for a minute or two before talking with God about what you wrote above.",
        ],
        "quote": {"text": "… he who began a good work in you will carry it on to completion until the day of Christ Jesus.", "ref": "Philippians 1:6 NIV"},
        "reflection": "Journal 2-3 words describing your faith journey so far, and one question you have about God, faith, or the Bible to bring to a pastor or trusted friend this week.",
    },
    # ---------------- WEEK 2: Living Like Jesus Lived ----------------
    {
        "day": 8,
        "week": 2,
        "slug": "who-am-i-becoming",
        "title": "Who Am I Becoming?",
        "summary": "Becoming a Christian begins with a choice to accept God's gift of forgiveness, followed by a lifelong process of becoming more like Jesus.",
        "scripture": [{"ref": "Matthew 22:37-40", "translation": "NLT", "link": yv_link("MAT", "22.37-40", "NLT")}],
        "body": [
            "Welcome to week two of our three-week journey (or week four, or five, or however long it takes you)! Last week, we discovered that being a Christian begins with a choice to accept God's gift of forgiveness, followed by a lifelong process of becoming more like Jesus.",
            "Now, you might be wondering: What does it actually look like to become more like Jesus? Is it even possible to become more like Jesus? After all, Jesus is God, the Creator of everything, who has always existed and who never sinned. How could we possibly become like Him?",
            "How do you become a concert violinist, pro basketball player, or expert chef? First, you start somewhere. You say yes to a new way of life. Saying yes doesn't make you a master, but it does make you a learner in the process of becoming something more.",
            "As a learner, you gain knowledge, develop relationships, practice skills, and overcome setbacks. Learners also make mistakes, fall short, and keep moving forward. The word Jesus used for a learner is “disciple.” When we said yes to Jesus, we said yes to a lifelong process of becoming His disciples.",
            "For the next two weeks, we're going to explore how to be a disciple of Jesus. First, we'll learn about some of the habits and mindsets Jesus valued and lived out, also called spiritual practices. Then, we'll explore how Jesus loved and how we can show the same kinds of sacrificial care to others.",
            "During Jesus' time on Earth, some people were trying to figure out whether Jesus was really God's Son. They asked Him, “What's the greatest command of God?” He responded:",
        ],
        "quote": {"text": "… “You must love the Lord your God with all your heart, all your soul, and all your mind.” This is the first and greatest commandment. A second is equally important: ‘Love your neighbor as yourself.' The entire law and all the demands of the prophets are based on these two commandments.", "ref": "Matthew 22:37-40 NLT"},
        "closing": "Jesus summed up all of God's words to us as: Love God and love your neighbor as yourself. Becoming the kind of person who loves God and loves your neighbors is a process that will take your whole life. Every disciple experiences setbacks and failures. If you're like the rest of us, you may have experienced some of those setbacks already. When we fall short, we don't need to hide or run from God or others. His forgiving kindness is always available to help you continue becoming more like Jesus.",
        "prayer": "God, You see the mistakes I make. Thank You for forgiving me and guiding me as I become more like Jesus. Holy Spirit, will You help me see one step I can take to grow in love for You, myself, and others today? In Jesus' name, amen.",
    },
    {
        "day": 9,
        "week": 2,
        "slug": "how-do-i-read-the-bible",
        "title": "How Do I Read the Bible?",
        "summary": "Two ways Jesus used the Bible: to show God's love for people, and always in context.",
        "scripture": [{"ref": "Matthew 22:37-40", "translation": "NLT", "link": yv_link("MAT", "22.37-40", "NLT")}],
        "body": [
            "To Jesus, the Bible was so much more than words on a page. That's because God shaped the Bible to show followers of Jesus how to live and love across generations. But how do we use it? After all, it's a massive book full of ancient poetry, songs, history, laws, and letters.",
            "Modern Bibles contain two main sections. The first is called the Hebrew Bible or the Old Testament. The second is the New Testament. The New Testament was written after the life of Jesus. But even though Jesus only read from the Old Testament, how He used the Old Testament can inform how we read the whole Bible.",
            "Let's start by looking at two ways Jesus used the Bible.",
        ],
        "list_headed": [
            {"head": "1. Jesus used the Bible to show God's love for people.", "body": "In Matthew 22, a person asks Jesus, “What is the greatest command from God?” Sound familiar? We read this passage yesterday, but let's reread it and see how it can help us read the Bible better."},
        ],
        "quote": {"text": "… “You must love the Lord your God with all your heart, all your soul, and all your mind.” This is the first and greatest commandment. A second is equally important: ‘Love your neighbor as yourself.' The entire law and all the demands of the prophets are based on these two commandments.", "ref": "Matthew 22:37-40 NLT"},
        "body2": [
            "Jesus quoted the Bible to help people understand the heart of God and how He calls us to live. So, as we read the Bible, it can be helpful to ask the question, “How do these words help me love God and love others?”",
        ],
        "list_headed2": [
            {"head": "2. Jesus used the Bible in context.", "body": "In Matthew 4, Jesus is tempted by a spiritual enemy. The enemy quotes the Bible to make his lies sound like spiritual wisdom—but Jesus isn't fooled. That's because He understands the value of context. Ancient authors wrote the Bible with different languages and perspectives than we have today. When we read the Bible, it's important to ask a lot of questions like, “Who wrote this? Who were they writing to? What genre is this book (poetry, history, letter, etc.)? And what's happening in this book or chapter?” When we don't read in context, we risk missing the point the Bible is trying to make."},
        ],
        "closing": "When in doubt, ask yourself: How do these words from the Bible help me to love God and my neighbors? The Bible is more than just words on a page. It's a gift from God that has the power to transform us from the inside out. This is why it can be helpful to think of this practice as studying or learning the Bible instead of just reading it. The Bible is meant to be read, reread, explored, meditated on, and reflected on—over and over again.",
    },
    {
        "day": 10,
        "week": 2,
        "slug": "how-do-i-pray",
        "title": "How Do I Pray?",
        "summary": "Jesus made prayer a priority. Here's how He prayed—and how you can build the same habit.",
        "scripture": [{"ref": "Luke 6:12-13", "translation": "NIV", "link": yv_link("LUK", "6.12-13", "NIV")}],
        "body": [
            "Jesus spent a lot of time in prayer. The Bible tells us on multiple occasions, Jesus stayed up all night to pray. Why? He's God, right? Why does He need to pray?",
            "During Jesus' time on Earth, He was fully God and fully human. As a human, He was like us and needed to use consistent habits to sustain His relationship with God, His Father.",
            "For Jesus, prayer was a source of direction, courage, and connection with God—and prayer can do the same for us. Check out how Jesus prepared to make a big choice—choosing a core group of followers who would end up founding the church.",
        ],
        "quote": {"text": "One of those days Jesus went out to a mountainside to pray, and spent the night praying to God. When morning came, he called his disciples to him and chose twelve of them, whom he also designated apostles …", "ref": "Luke 6:12-13 NIV"},
        "body2": [
            "Jesus didn't just pray before making big decisions. He also prayed to experience closeness with God and to find strength before facing difficult situations. How can we develop a habit of prayer like Jesus?",
            "First, let's talk about how Jesus didn't pray. Jesus didn't fill His prayers with fancy words. Jesus didn't pray to impress the people around Him. Jesus didn't pray with a list of demands for God.",
            "Prayer is meant to be a personal conversation with God—like you would have with friends, family, or a mentor. Take the pressure off. Let go of how you think you should pray and just talk with God openly and honestly.",
            "So, how did Jesus pray? Jesus made prayer a priority. Jesus prayed in the presence of others. Jesus prayed on His own. Jesus asked others to pray for Him.",
        ],
        "closing": "Today, let's start a habit of prayer. Simply take a few minutes on your way home from work or before going to bed to talk with God. Tell Him what you're thankful for, ask Him for what you need, and listen to His voice. As you do, you'll discover a closer relationship with Jesus every day.",
    },
    {
        "day": 11,
        "week": 2,
        "slug": "how-do-i-make-friends",
        "title": "How Do I Make Friends?",
        "summary": "Jesus was their Savior, but He was also their friend—close relationships are an essential spiritual practice.",
        "scripture": [{"ref": "John 15:15", "translation": "NIV", "link": yv_link("JHN", "15.15", "NIV")}],
        "body": [
            "Throughout His ministry, Jesus surrounded Himself with people who could encourage Him, pray for Him, and support Him. Yes, Jesus was their Savior, but He was also their friend. Here's how Jesus talked about His relationship with His followers:",
        ],
        "quote": {"text": "“I no longer call you servants, because a servant does not know his master's business. Instead, I have called you friends, for everything that I learned from my Father I have made known to you.”", "ref": "John 15:15 NIV"},
        "body2": [
            "If Jesus chose close relationships, it's a good idea for us to find close relationships with other followers of Jesus, too.",
            "Sometimes life can feel impossibly difficult, and in those moments, we need people we can lean on for prayer, guidance, and support. In times of joy, celebrating with friends can make those moments even more meaningful.",
            "These things are true about relationships because God made us to be like Him. God is in life-giving relationship with Himself as the Father, Son, and Holy Spirit, and He desires a relationship with us. That's why surrounding yourself with people who follow Jesus is an essential spiritual practice—when you do so, you're following God's example.",
            "Do you have the close relationships you need in life? People who encourage you in your relationship with Jesus and support you through life's highs and lows? If not, think about how you can invest in the relationships you already have or find the friendships you need.",
            "If you don't currently have close, Jesus-following friends, finding a small group of fellow Jesus followers is a great place to start.",
        ],
        "closing": "Finding and making friends can feel awkward or intimidating, but finding your people is worth the initial discomfort. It's life-giving to have friends who celebrate you, support you, and encourage you to keep getting to know Jesus every day.",
    },
    {
        "day": 12,
        "week": 2,
        "slug": "what-is-worship",
        "title": "What Is Worship?",
        "summary": "Worship is what happens when you join a group of Jesus followers, learn Scripture, pray to God, and build life-changing relationships.",
        "scripture": [
            {"ref": "Psalm 113:5-8", "translation": "NLT", "link": yv_link("PSA", "113.5-8", "NLT")},
            {"ref": "Psalm 116:4-7", "translation": "NLT", "link": yv_link("PSA", "116.4-7", "NLT")},
        ],
        "body": [
            "What happens when you join a group of Jesus followers, learn Scripture, pray to God, and build life-changing relationships? Worship.",
            "Jesus' life was characterized by worship. What words come to mind when you think about worship? Maybe words like music, instruments, songs—which makes sense! Singing is certainly a way Jesus worshiped.",
            "On the evening before Jesus' execution, He shared a meal with His friends. It was Passover, an important holiday for the Jewish people.",
            "At the end of the meal, Jesus and the disciples sang together. In ancient Jewish culture, people often sang Psalms 113-118 to celebrate Passover. It's likely that Jesus sang these words of praise:",
        ],
        "quote": {"text": "Who can be compared with the Lord our God, who is enthroned on high? He stoops to look down on heaven and on earth. He lifts the poor from the dust and the needy from the garbage dump. He sets them among princes, even the princes of his own people!", "ref": "Psalm 113:5-8 NLT"},
        "quote2": {"text": "I called on the name of the Lord: “Please, Lord, save me!” How kind the Lord is! How good he is! So merciful, this God of ours! The Lord protects those of childlike faith; I was facing death, and he saved me. Let my soul be at rest again, for the Lord has been good to me.", "ref": "Psalm 116:4-7 NLT"},
        "body2": [
            "These words of praise express awe and celebrate God's qualities and character. He's the Creator and Ruler of the world. He doesn't need to care for us, but He does because He loves us. He pays special attention to people in need of physical or spiritual support.",
            "Today, like the Passover celebration, worship services are used to create space for people to worship God together. Worship songs give Jesus followers the opportunity to remember who God is and what He's done, and give Him the praise He deserves.",
            "Singing is one way we can worship God, but worship goes beyond something we do through music. We worship whenever we express our devotion to God. When we worship God, we're recognizing His awesome qualities and the amazing things He's done.",
            "Seeing a sunset, witnessing the birth of a child, or experiencing an answer to prayer can also create moments of praise. Any moment that reminds us of God's qualities and character is an opportunity for worship.",
            "This weekend, you'll have the opportunity to worship God through singing with other followers of Jesus at church. But don't wait until then to worship.",
        ],
        "closing": "Take a few minutes to consider what you're thankful for. Maybe it's the beauty of God's creation, a relationship, or God's forgiveness through Jesus. Express your gratitude to God for who He is and what He's done.",
    },
    {
        "day": 13,
        "week": 2,
        "slug": "how-do-i-stop-doing-whats-bad-for-me",
        "title": "How Do I Stop Doing What's Bad for Me?",
        "summary": "Feeling tempted isn't a sin. Here's how Jesus overcame temptation—and how you can too.",
        "scripture": [{"ref": "1 Corinthians 10:13", "translation": "NIV", "link": yv_link("1CO", "10.13", "NIV")}],
        "body": [
            "Do you ever want to do something even though you know it's wrong?",
            "For three years, everything about Jesus' life was uncomfortable. He shared uncomfortable truths with people in power, endured daily attacks from His critics, and regularly heard about plots to kill Him. But early in His story, He received an offer to skip past all the suffering and take an easier route.",
            "For 40 days, Jesus spent time alone in the desert without food. While He was vulnerable, the devil offered Him an easy way to escape suffering.",
            "We're tempted when we're offered a shortcut to something we want. Feeling tempted isn't a sin. But giving in to temptation can compromise our integrity and lead to a painful cycle of poor choices. How do we overcome temptation? By looking to Jesus.",
            "Jesus' spiritual practices helped Him overcome temptation. Jesus knew the Bible, and He also knew His purpose—and how living it out would include making hard, uncomfortable choices for the good of others. Only by making those choices could He change the world. No easy way out and no shortcuts.",
            "In other words, Jesus knew who He was and whose He was. So He refused to compromise His identity and calling for momentary pleasure or relief.",
            "We face temptations every day, both big and small, that can distract us from who we're becoming. Here's the good news: God wants to help you overcome temptation. Read what one Jesus follower had to say about temptation.",
        ],
        "quote": {"text": "No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can endure it.", "ref": "1 Corinthians 10:13 NIV"},
        "closing": "Let's be like Jesus and prepare for temptation before it strikes. We do this by studying, believing, and living out God's truths in the Bible, asking God for help through prayer, sharing vulnerably with others, and looking for the opportunities God provides to escape temptation. Sometimes the opportunity God provides can look like joining a recovery group, talking with a healthcare professional, or meeting with a pastor to find the tools you need to find freedom.",
        "prayer": "Dear God, thank You for always offering me another chance. Help me to recognize and resist temptation when it comes. In Jesus' name, amen.",
    },
    {
        "day": 14,
        "week": 2,
        "slug": "why-does-jesus-rest",
        "title": "Why Does Jesus Rest?",
        "summary": "We can only be as helpful as we are healthy. Rest—like Jesus practiced it—is worship, not laziness.",
        "scripture": [{"ref": "Luke 5:15-16", "translation": "NIV", "link": yv_link("LUK", "5.15-16", "NIV")}],
        "body": [
            "Do you ever feel anxious about everything going on during the week? Or do you wish you had more time for the people in your life? If so, you're in good company. Life often seems to demand for us to be busy. But Jesus invites us to a different (and better) way of living.",
            "Check out this surprising passage from the life of Jesus:",
        ],
        "quote": {"text": "Yet the news about him spread all the more, so that crowds of people came to hear him and to be healed of their sicknesses. But Jesus often withdrew to lonely places and prayed.", "ref": "Luke 5:15-16 NIV"},
        "body2": [
            "Think about what this passage is saying. People wanted to hear Jesus speak and receive healing—yet Jesus chose to walk away so He could rest. When He sacrificed productivity and opportunities to help others in order to rest, it was a good thing. Why?",
            "We can only be as helpful as we are healthy. So like Jesus, we can set boundaries with our time and purposefully slow down. All humans need rest, and because Jesus was fully God and fully man while on Earth, that limitation was true of Him, too.",
            "Rest is also worship. The Bible begins with an account of God creating the world. The story uses a seven-day structure to describe God's work. On the sixth day God created people, but the seventh day was a day of rest. Why is that important? Because humanity's first full day on Earth was a day of rest—not work.",
            "Throughout the Bible, the seventh day of the week is called the Sabbath. On that day, people are invited to worship by not doing work. But how is this worship?",
            "It's easy to forget this basic spiritual truth: God is in control; we're not. When we forget, we tend to try to control our lives through work. We begin obsessing over our to-do lists and worry about falling behind.",
            "When we choose to take a break from our tasks and to-do lists, we're making a declaration that late tasks, unfolded laundry, and unread emails don't threaten God's plan for the world. That's why the Sabbath, a time devoted to rest, is worship.",
            "You might work long hours and have people who depend on you. Don't feel guilty if you're not able to take a full day off each week to rest. Instead, find moments to rest when you can. Jesus did the same. Once, when He was tired, He simply sat down by a well. Another time, He took a nap in a boat.",
        ],
        "reflection": "How might you add rest into each week, and how might you add rest into each day?",
    },
    # ---------------- WEEK 3: Loving Like Jesus Loved ----------------
    {
        "day": 15,
        "week": 3,
        "slug": "how-do-i-love-like-jesus-loved",
        "title": "How Do I Love Like Jesus Loved?",
        "summary": "Jesus' definition of greatness: the one who is least among you all is the greatest.",
        "scripture": [{"ref": "Luke 9:46-48", "translation": "NIV", "link": yv_link("LUK", "9.46-48", "NIV")}],
        "body": [
            "Welcome to the final week of our journey! Last week, we started some spiritual practices to help us live the way Jesus lived. We witnessed how His mindsets, practices, and habits made way for His ministry. This week, we'll explore how Jesus loved. In other words, how did Jesus relate to other people? How did He make people feel? And how did He use His words and actions to accomplish His purpose?",
            "Let's check out an argument Jesus chose to break up. It happened between a few of His friends and followers:",
        ],
        "quote": {"text": "An argument started among the disciples as to which of them would be the greatest. Jesus, knowing their thoughts, took a little child and had him stand beside him. Then he said to them, “Whoever welcomes this little child in my name welcomes me; and whoever welcomes me welcomes the one who sent me. For it is the one who is least among you all who is the greatest.”", "ref": "Luke 9:46-48 NIV"},
        "body2": [
            "The disciples had the wrong idea of how to achieve greatness as followers of Jesus. Maybe they thought the greatest was the one who performed the greatest miracles or knew the Bible best. But Jesus has a different definition of greatness.",
            "Jesus said that the person who welcomes a child is the greatest. What? Why does that make someone great? Jesus explained, “It is the one who is least among you all who is the greatest.”",
            "In other words, Jesus said that the greatest in God's eyes is the person who isn't seeking prestige, power, or a platform. Instead, they're seeking to humbly serve.",
            "Jesus, who is God, came as a baby to a humble family in a small village. When He grew up, He didn't order His followers around like servants. Instead, He patiently led them and looked for ways to meet their needs.",
            "That's why He tells us the way to be the greatest in the kingdom is to consistently do good without seeking attention or praise. Service levels playing fields. It helps us see one another as God sees us—all equals, made in His image. And it helps us see God—great and powerful and wonderful and deserving of all praise—as the One we serve as we serve others.",
            "If we want to love like Jesus, we need to pursue His version of greatness. Jesus lived an others-focused life that led Him to hospitality, service, forgiveness, generosity, and telling others about God's love. We'll explore each of these topics this week.",
        ],
        "closing": "So, what are you pursuing in life? The world invites us to be “great” by pursuing personal goals that lead us to influence and comfort. Jesus invites us to a different kind of greatness—one focused on raising others up.",
    },
    {
        "day": 16,
        "week": 3,
        "slug": "welcoming-others",
        "title": "Welcoming Others",
        "summary": "Jesus made people feel at home everywhere He went. We call this hospitality.",
        "scripture": [{"ref": "Luke 8:1-3", "translation": "NIV", "link": yv_link("LUK", "8.1-3", "NIV")}],
        "body": [
            "Have you ever felt “at home” in a place that wasn't your home? Maybe you get that feeling in a church, coffee shop, or at a friend's house. Or you might feel at home with a family member or friend.",
            "All of us feel “at home” when we feel safe to be ourselves—not worried about doing or saying the wrong thing because we feel loved and accepted as we are.",
            "We all want a place to feel “at home.” Jesus knows this, and that's why He made people feel at home everywhere He went. He did this by taking time to welcome people into His life, listening, showing empathy, and giving them permission to be honest. We call this hospitality.",
            "In Luke 8, we find a list of people who followed Jesus during His ministry. These were the people Jesus welcomed into His life. They were flawed people, but Jesus' hospitality turned these different individuals into a kind of family.",
        ],
        "quote": {"text": "… The Twelve were with him, and also some women who had been cured of evil spirits and diseases: Mary (called Magdalene) from whom seven demons had come out; Joanna the wife of Chuza, the manager of Herod's household; Susanna; and many others. These women were helping to support them out of their own means.", "ref": "Luke 8:1-3 NIV"},
        "body2": [
            "These people couldn't have been more different. The Twelve were from different social classes and came from different backgrounds. They would have had countless opportunities to disagree. But Jesus welcomed each of them, just as they were, into His family.",
            "Then there's Mary Magdalene, a woman Jesus freed from spiritual oppression. Despite her rough background, Jesus welcomed her into His inner circle.",
            "Finally, let's talk about Joanna. She was the wife of King Herod's household manager. King Herod was no friend of Jesus. In Matthew 14, Herod ordered the execution of Jesus' cousin, John the Baptist. But Jesus welcomed Joanna to be a part of His ministry.",
            "Hospitality breaks down social barriers and builds unlikely friendships. Hospitality invites us to be less critical and more curious. It helps people realize their God-given value and potential. It builds empathy and turns strangers into neighbors.",
        ],
        "reflection": "How do we show hospitality? You can start by thinking about a time someone made you feel seen, cared for, and included. How did their hospitality change you? Then, consider how you might create the same feeling and impact for someone else by partnering with God to become hospitable.",
    },
    {
        "day": 17,
        "week": 3,
        "slug": "becoming-a-generous-person",
        "title": "Becoming a Generous Person",
        "summary": "Generosity means sharing what you have to help someone else—your money, but also your time, skills, and resources.",
        "scripture": [{"ref": "Luke 3:11", "translation": "NIV", "link": yv_link("LUK", "3.11", "NIV")}],
        "body": [
            "In the months leading up to Jesus' ministry, rumors spread about the coming Savior of the world. People had lots of opinions about what He'd be like, so they went to Jesus' cousin for answers.",
            "Many wanted to know how they could get ready for the Savior's arrival. John the Baptist told them this:",
        ],
        "quote": {"text": "… “Anyone who has two shirts should share with the one who has none, and anyone who has food should do the same.”", "ref": "Luke 3:11 NIV"},
        "body2": [
            "According to John, generosity makes room in our hearts for Jesus.",
            "Generosity means sharing what you have to help someone else. See how simple that definition is? It includes our money but also everything else we have—our time, our skills, our resources.",
            "So, how can you become a generous person? It's not complicated, but it's not always easy. Here are a few ways to be generous.",
        ],
        "list_headed": [
            {"head": "1. Ask yourself, “What do I need?”", "body": "God wants us to enjoy the things we have. But we don't own our stuff. God does, and He calls us to share what we have with others. So ask yourself, “What do I really need?”"},
            {"head": "2. Ask yourself, “What do I have to share?”", "body": "Maybe you have plenty of spare time or a skill you've developed. Or maybe you have money that could bless others. No matter what it is, if you have something, you can probably find a way to share it."},
            {"head": "3. Ask yourself, “What does my community need?”", "body": "The people around you have needs you can meet. Maybe your neighbor has experienced a loss and simply being generous with your words and presence could make a difference. Or your local food bank might need volunteers or donations. Your local church is able to open its doors to the community because of generous givers. Researching the needs in your community could inspire generous creativity."},
        ],
        "closing": "Jesus followers often give regularly out of what they earn each week to their church. Why? Because the church is doing God's work in your community. So when we give to the church, we provide the church with more opportunities to make an eternal impact. Jesus was generous, and He invites each of us to live like Him. You have what it takes to be a generous person. You can start by identifying what you need, what you have to share, and what your community needs.",
    },
    {
        "day": 18,
        "week": 3,
        "slug": "noticing-and-meeting-needs",
        "title": "Noticing and Meeting Needs",
        "summary": "Jesus is brilliant at noticing needs—and He used what He had to meet them. So can we.",
        "scripture": [{"ref": "John 13:15-17", "translation": "NIV", "link": yv_link("JHN", "13.15-17", "NIV")}],
        "body": [
            "Today, let's talk about a skill Jesus shows us in the Bible that's easy to overlook. On the surface, it seems ordinary. But it's actually one of the most important ways we can love like Jesus.",
            "Jesus is brilliant at noticing needs.",
            "Dozens of stories in the Bible begin with Jesus walking somewhere and noticing someone in need. Sometimes their need was visible and physical. Other times it was under the surface or spiritual. Either way, Jesus saw the needs of people around Him.",
            "Once Jesus noticed a need, He used what He had to meet it. Sometimes, He'd use His words to meet a spiritual or emotional need. He'd ask for God's help to meet a physical need with the power of God's Spirit living in Him.",
            "As followers of Jesus, we're called to live others-focused lives. One of the best ways to do that is by serving others. We serve others when we notice their needs and use what we have to meet those needs. Sometimes, we can't meet a need on our own, but that doesn't mean we can't help. Instead, it's an opportunity to ask for God's help to meet a need that's beyond us.",
            "Remember, as a follower of Jesus, you have the Holy Spirit living in you.",
            "On the night before His execution on the cross, Jesus gathered His disciples and washed their feet. Foot washing before meals was a common practice in that day and, as you might imagine, was a task for the lowest of servants. But Jesus, God in human form, chose to wash the feet of His flawed human followers.",
            "Here's what He said after He washed their feet:",
        ],
        "quote": {"text": "“I have set you an example that you should do as I have done for you. Very truly I tell you, no servant is greater than his master, nor is a messenger greater than the one who sent him. Now that you know these things, you will be blessed if you do them.”", "ref": "John 13:15-17 NIV"},
        "closing": "Followers of Jesus seek to serve others. We notice needs and, with God's help, we meet them. So keep your eyes open today. Who around you might need an encouraging word, prayer for physical or emotional healing, or help with a task? As you live an others-focused life, you'll experience greater closeness with God.",
    },
    {
        "day": 19,
        "week": 3,
        "slug": "forgiving-others",
        "title": "Forgiving Others",
        "summary": "We are forgiven people—so we forgive others. Not seven times, but seventy-seven times.",
        "scripture": [
            {"ref": "Luke 23:34", "translation": "NIV", "link": yv_link("LUK", "23.34", "NIV")},
            {"ref": "Matthew 18:21-22", "translation": "NIV", "link": yv_link("MAT", "18.21-22", "NIV")},
        ],
        "body": [
            "Forgiveness is a big deal to God. He loves to forgive. That's why, throughout the Bible, God generously offers forgiveness and second chances to all kinds of people.",
            "As Christians, we know what it's like to be forgiven. We've all made mistakes and hurtful choices. But God offers us forgiveness through Jesus—not because we earned it, but because God loves to forgive.",
            "It's no surprise that Jesus forgave a lot of people during His ministry. The Gospels tell us He forgave people's sins. At the end of Jesus' ministry, He was beaten, humiliated, and hung on a cross to die. Despite all of the pain He experienced, some of His last words were:",
        ],
        "quote": {"text": "…“Father, forgive them, for they do not know what they are doing.” …", "ref": "Luke 23:34 NIV"},
        "body2": [
            "That's how much Jesus loves to forgive. He sees the God-given potential in every person and doesn't jump to judgment.",
            "What does this mean for followers of Jesus? You've probably already guessed it: Followers of Jesus forgive others.",
            "One of Jesus' followers, Peter, asked Jesus about forgiveness. He wondered how often he needed to forgive someone who kept messing up. Relatable question, right? Matthew 18 tells us:",
        ],
        "quote2": {"text": "Then Peter came to Jesus and asked, “Lord, how many times shall I forgive my brother or sister who sins against me? Up to seven times?” Jesus answered, “I tell you, not seven times, but seventy-seven times.”", "ref": "Matthew 18:21-22 NIV"},
        "body3": [
            "Now, this doesn't mean Jesus wants us to count how many times we forgive someone and then cut them off after seventy-seven. Instead, He's encouraging us to pursue forgiveness no matter what.",
            "Forgiveness doesn't mean forgetting what was said or done, and it doesn't mean excusing what someone's done. Instead, it means letting go of the need to get back or get even. Forgiveness is a declaration that you refuse to let anger, hurt, or betrayal control your mind and actions.",
            "Forgiveness can also include boundaries. Sometimes we need to forgive and love people from a distance for the health of ourselves and others.",
        ],
        "closing": "We are forgiven people—so we forgive others. It's not always easy, and it might feel impossible sometimes, but it's one of the best ways we can be like our forgiving God.",
        "prayer": "Dear God, thank You for forgiving me, even when I don't deserve it. Will You show me someone I need to forgive and give me the strength to forgive like You? In Jesus' name, amen.",
    },
    {
        "day": 20,
        "week": 3,
        "slug": "telling-people-about-jesus",
        "title": "Telling People About Jesus",
        "summary": "Jesus calls us to go into our neighborhoods, workplaces, and all over the world, loving people how He does.",
        "scripture": [{"ref": "Matthew 28:18-20", "translation": "NIV", "link": yv_link("MAT", "28.18-20", "NIV")}],
        "body": [
            "On the last day of Jesus' ministry, He left His disciples with some parting words:",
        ],
        "quote": {"text": "… “All authority in heaven and on earth has been given to me. Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, and teaching them to obey everything I have commanded you. And surely I am with you always, to the very end of the age.”", "ref": "Matthew 28:18-20 NIV"},
        "body2": [
            "Let's go through this passage together.",
            "“All authority in heaven and on earth has been given to me.” Jesus is the ruler of heaven and earth. He's the King, and we live in His Kingdom. Jesus' Kingdom isn't like any other nation on Earth. That's because it's filled with people who choose to live and love like Jesus through service, generosity, hospitality, and forgiveness.",
            "“Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, and teaching them to obey everything I have commanded you.” Not everyone has experienced Jesus' grace, forgiveness, and acceptance. Jesus wants to change that, and He wants our help. So He calls us to go into our neighborhoods, workplaces, and all over the world, loving people how Jesus does and showing them the joy, passion, and purpose of a life that's fully devoted to Him.",
            "This could look like inviting your neighbors to church, sharing the story of what God has done in your life, or any number of ways God can use you to share and show His love to others around you.",
            "“And surely I am with you always, to the very end of the age.” As we go into the world telling people about Jesus, we're not alone. Jesus is with us every step of the way through the Holy Spirit. The Spirit encourages us and gives us strength as we pursue our mission.",
            "How do we obey Jesus' command to share His message and way of life with the world? Christians often call our approach to sharing Jesus with the world “missions.” We get involved in missions locally by getting to know our neighbors and looking for ways to meet the needs of people in our communities. As we get to know others, we share our stories and the way Jesus is changing our lives.",
        ],
        "closing": "As you invest in your neighborhood or city, look for ways to support global missions as well. There are full-time missionaries and missions organizations at work all over the world, focused on needs like Bible translation, education, disaster relief, and fighting human trafficking. We can all support missions through prayer, giving, or looking for opportunities to volunteer.",
    },
    {
        "day": 21,
        "week": 3,
        "slug": "what-happens-next",
        "title": "What Happens Next?",
        "summary": "You said yes. Now keep saying yes to Jesus every day—seek progress, not perfection.",
        "scripture": [{"ref": "Philippians 1:6, 9", "translation": "NLT", "link": yv_link("PHP", "1.6", "NLT")}],
        "body": [
            "You're almost finished reading this book, but your story is just beginning. We're so proud of you for going through this journey. Today, we'd like to share these words from an early Jesus follower named Paul.",
        ],
        "quote": {"text": "… I am certain that God, who began the good work within you, will continue his work until it is finally finished on the day when Christ Jesus returns.", "ref": "Philippians 1:6 NLT"},
        "body2": [
            "Paul wrote these words to a group of Jesus followers two thousand years ago. The whole chapter is full of encouragement for people doing their best to follow Jesus each day. They weren't perfect, but they were making progress, like we are.",
            "We don't know where you were when Jesus found you and you chose to follow Him. And we don't know the challenges you've had to overcome in the past few weeks. But we are confident that God has started a good work in you, and He will continue His work for the rest of your life.",
            "Our prayer for you is the same prayer Paul shared with some of the first Jesus followers in the ancient city of Philippi:",
        ],
        "quote2": {"text": "I pray that your love will overflow more and more, and that you will keep on growing in knowledge and understanding.", "ref": "Philippians 1:9 NLT"},
        "body3": [
            "You said yes. Now keep saying yes to Jesus every day. Seek progress, not perfection. God is love, so He won't abandon you when life gets hard or when you make a mistake. It won't always feel easy, but as you make progress, you'll witness God working all around you as you live and love like Jesus.",
            "So what happens next? Your journey of following Jesus is unique:",
        ],
        "list": [
            "You might choose to find friends through a small group.",
            "You might choose to get to know more about your church.",
            "You might choose to use your gifts to make a difference through serving.",
            "Or you could choose something completely different!",
        ],
        "closing": "This weekend at church, let your pastor know you finished this book. They'd love to congratulate you and help you discover your best next step as you follow Jesus.",
        "next_steps": [
            "Getting baptized",
            "Finding a mentor",
            "Joining a small group",
            "Sharing your decision to follow Jesus with a friend or family member",
            "Starting to serve",
            "Seeking counseling",
            "Inviting someone to church",
            "Giving back to your church and community",
        ],
    },
]

WEEK_TITLES = {
    1: "Starting to Follow Jesus",
    2: "Living Like Jesus Lived",
    3: "Loving Like Jesus Loved",
}

assert len(DAYS) == 21, f"Expected 21 days, got {len(DAYS)}"
